#ifndef APEX_CIS_GENE_TABLE_READER_H
#define APEX_CIS_GENE_TABLE_READER_H

#include <string>
#include <map>
#include <vector>
#include <memory>
#include <fstream>
#include <string>
#include <iostream>
#include <regex>
#include <optional>
#include "reader_util.h"
#include <boost/iostreams/filtering_streambuf.hpp>
#include <boost/iostreams/filter/gzip.hpp>

struct CisGeneRecord {
  std::string chrom;
  uint64_t start;
  uint64_t end;
  std::string gene;
  long double egene_pval;
  uint64_t n_samples;
  uint64_t n_covar;
  double resid_sd;
  uint64_t n_cis_variants;
};

/**
 * Class to read stepwise conditional analysis results as generated by apex meta --stepwise.
 */
class CisGeneTableReader {
protected:
  std::vector<std::shared_ptr<CisGeneRecord>> records;
  std::map<std::string, std::shared_ptr<CisGeneRecord>> index;
public:
  CisGeneTableReader(const std::string &file);
  void load(const std::string &file);
  std::shared_ptr<CisGeneRecord> get_record(const std::string &i);

  bool operator==(const CisGeneTableReader& other);
};

#endif //APEX_CIS_GENE_TABLE_READER_H