#ifndef APEX_META_STEPWISE_READER_H
#define APEX_META_STEPWISE_READER_H

#include <string>
#include <map>
#include <vector>
#include <memory>
#include "reader_util.h"
#include "miscUtils.hpp"

struct StepwiseRecord {
  std::string gene;
  std::vector<std::string> studies;
  std::string signal;
  std::string variant;
  double beta;
  double se;
  long double pval_joint;
  long double pval_signal;
  long double pval_marginal;
  long double pval_stepwise;
  double log_pval_joint;
  double log_pval_signal;
  double log_pval_marginal;
  double log_pval_stepwise;
};

/**
 * Class to read stepwise conditional analysis results as generated by apex meta --stepwise.
 */
class StepwiseReader {
protected:
  std::vector<std::shared_ptr<StepwiseRecord>> records;
  std::map<std::string, std::shared_ptr<StepwiseRecord>> index;

  /** Compare p-values using log scale values only **/
  bool use_log;
public:
  StepwiseReader(const std::string &file, bool use_log = false);
  void load(const std::string &file);
  std::shared_ptr<StepwiseRecord> get_record(const std::string &i);

  bool operator==(const StepwiseReader& other);
};

#endif //APEX_META_STEPWISE_READER_H