plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - benchmarking/README.md
  - input_files/README.md
  - mode_cis/README.md
  - mode_trans/README.md
  - mode_meta/README.md
