plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - benchmarking.md
  - input_files.md
  - mode_cis.md
  - mode_trans.md
  - mode_meta.md
